import { mkdir, unlink, writeFile } from "node:fs/promises";
import path from "node:path";

import { env } from "../config/env.js";
import { logger } from "../utils/logger.js";

// Where uploaded files (venue photos) live. Keys look like
// "venues/<venueId>/<uuid>.webp" and are always generated by the server.

export interface StoredFile {
  key: string;
  url: string;
}

export interface FileStorage {
  put(key: string, body: Buffer, contentType: string): Promise<StoredFile>;
  remove(keys: string[]): Promise<void>;
}

/** Public URL prefix for locally stored files (served by app.ts). */
export const LOCAL_UPLOADS_ROUTE = "/api/uploads";

export const uploadsDir = path.resolve(env.UPLOADS_DIR);

const localStorage: FileStorage = {
  async put(key, body) {
    const target = path.join(uploadsDir, key);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, body);
    // Relative URL: the frontend reaches /api on its own origin (Vite proxy).
    return { key, url: `${LOCAL_UPLOADS_ROUTE}/${key}` };
  },

  async remove(keys) {
    await Promise.all(
      keys.map((key) =>
        unlink(path.join(uploadsDir, key)).catch((error: NodeJS.ErrnoException) => {
          if (error.code !== "ENOENT") throw error;
        })
      )
    );
  },
};

// Supabase Storage via its REST API: https://supabase.com/docs/reference/api/storage
const supabaseStorage = (): FileStorage => {
  const baseUrl = env.SUPABASE_URL!.replace(/\/+$/, "");
  const bucket = env.SUPABASE_BUCKET;
  const headers = {
    Authorization: `Bearer ${env.SUPABASE_SERVICE_KEY}`,
    apikey: env.SUPABASE_SERVICE_KEY!,
  };

  return {
    async put(key, body, contentType) {
      const response = await fetch(`${baseUrl}/storage/v1/object/${bucket}/${key}`, {
        method: "POST",
        headers: {
          ...headers,
          "Content-Type": contentType,
          "Cache-Control": "max-age=31536000",
          "x-upsert": "true",
        },
        body: new Uint8Array(body),
      });

      if (!response.ok) {
        throw new Error(`Supabase upload failed (${response.status}): ${await response.text()}`);
      }

      return { key, url: `${baseUrl}/storage/v1/object/public/${bucket}/${key}` };
    },

    async remove(keys) {
      if (keys.length === 0) return;

      const response = await fetch(`${baseUrl}/storage/v1/object/${bucket}`, {
        method: "DELETE",
        headers: { ...headers, "Content-Type": "application/json" },
        body: JSON.stringify({ prefixes: keys }),
      });

      if (!response.ok) {
        throw new Error(`Supabase delete failed (${response.status}): ${await response.text()}`);
      }
    },
  };
};

export const storage: FileStorage =
  env.STORAGE_DRIVER === "supabase" ? supabaseStorage() : localStorage;

/** Deletes files without failing the caller; orphaned files are only wasted space. */
export async function removeQuietly(keys: string[]) {
  try {
    await storage.remove(keys);
  } catch (error) {
    logger.error({ err: error, keys }, "Failed to delete stored files");
  }
}
